apiVersion: batch/v1
kind: Job
metadata:
  name: oes-autoconfigure-mahesh
spec:
 template:
    spec:
      containers:
      - command: ["sleep", "2"]
        image: quay.io/opsmxpublic/awsgit:v2-openssh-javalibs
        imagePullPolicy: IfNotPresent
        name: auto-configure-mahesh
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
