---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mahesh-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-cron
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: mahesh-job
  namespace: saiworkflows
